In [1]:
import os
from pathlib import Path

os.getcwd()
mb_dir = Path(os.getcwd()).parent.parent
os.chdir(mb_dir)
data_dir = str(mb_dir.parent / "data")
root_dir = str(mb_dir.parent)

import xarray as xr
import scipy.io as sio
import numpy as np

### Figure 2

In [8]:
import pandas as pd

df = pd.read_csv(f'{root_dir}/fig_data/monsoon_basic_metrics_2019_2024_new.csv')
df_bins = pd.read_csv(f'{root_dir}/fig_data/monsoon_bin_metrics_2019_2024.csv')

print(df_bins.columns)
sub = df_bins.loc[df_bins["model_label"] == "gencast"]
for col in sub.columns:
    if "auc" in col:
        print(col, sub[col].values[1])
5

Index(['model_label', 'horizon', 'fair_brier_d11_15', 'auc_d11_15',
       'fair_brier_skill_d11_15', 'fair_brier_d1_5', 'auc_d1_5',
       'fair_brier_skill_d1_5', 'fair_brier_d6_10', 'auc_d6_10',
       'fair_brier_skill_d6_10', 'fair_brier_later', 'auc_later',
       'fair_brier_skill_later', 'fair_brier_d16_20', 'auc_d16_20',
       'fair_brier_skill_d16_20', 'fair_brier_d21_25', 'auc_d21_25',
       'fair_brier_skill_d21_25', 'fair_brier_d26_30', 'auc_d26_30',
       'fair_brier_skill_d26_30'],
      dtype='object')
auc_d11_15 0.8430296463789962
auc_d1_5 0.9373177842565598
auc_d6_10 0.8558794946550048
auc_later 0.905329504155336
auc_d16_20 0.7907634775126584
auc_d21_25 0.728440424596445
auc_d26_30 0.7240201620501224

5

In [6]:
sub

,model_label,horizon,fair_brier_d11_15,auc_d11_15,fair_brier_skill_d11_15,fair_brier_d1_5,auc_d1_5,fair_brier_skill_d1_5,fair_brier_d6_10,auc_d6_10,...,fair_brier_skill_later,fair_brier_d16_20,auc_d16_20,fair_brier_skill_d16_20,fair_brier_d21_25,auc_d21_25,fair_brier_skill_d21_25,fair_brier_d26_30,auc_d26_30,fair_brier_skill_d26_30
1,gencast,15,0.077809,0.84303,0.090983,0.049575,0.937318,0.370941,0.07203,0.855879,...,-0.048950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,gencast,30,0.077809,0.84303,0.090983,0.049575,0.937318,0.370941,0.07203,0.855879,...,-0.286444,0.081456,0.790763,-0.009298,0.090486,0.72844,-0.043749,0.08788,0.72402,-0.019993

In [3]:
df_bins

,model_label,horizon,fair_brier_d11_15,auc_d11_15,fair_brier_skill_d11_15,fair_brier_d1_5,auc_d1_5,fair_brier_skill_d1_5,fair_brier_d6_10,auc_d6_10,...,fair_brier_skill_later,fair_brier_d16_20,auc_d16_20,fair_brier_skill_d16_20,fair_brier_d21_25,auc_d21_25,fair_brier_skill_d21_25,fair_brier_d26_30,auc_d26_30,fair_brier_skill_d26_30
0,fuxis2s,15,0.095477,0.722254,-0.092975,0.069074,0.786510,0.151953,0.078851,0.838069,...,-0.269131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,gencast,15,0.077809,0.843030,0.090983,0.049575,0.937318,0.370941,0.072030,0.855879,...,-0.048950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ifss2s,15,0.080823,0.792046,0.066656,0.048198,0.923210,0.403834,0.067832,0.857985,...,0.040757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ngcm,15,0.080672,0.825843,0.057531,0.051608,0.949433,0.345143,0.070289,0.884419,...,-0.013434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,clim,30,0.085597,0.788471,0.000000,0.078807,0.880175,0.000000,0.080519,0.838322,...,0.000000,0.080705,0.796265,0.000000,0.086694,0.768466,0.000000,0.086158,0.775784,0.000000
5,cond,30,0.084802,0.789335,0.009289,0.063436,0.917517,0.195057,0.076030,0.858722,...,-0.005367,0.080904,0.789878,-0.002463,0.086997,0.760536,-0.003502,0.086331,0.771026,-0.002015
6,fuxis2s,30,0.095477,0.722254,-0.092975,0.069074,0.786510,0.151953,0.078851,0.838069,...,-0.227307,0.106109,0.688865,-0.266311,0.108591,0.678680,-0.174954,0.089278,0.705151,-0.077614
7,gencast,30,0.077809,0.843030,0.090983,0.049575,0.937318,0.370941,0.072030,0.855879,...,-0.286444,0.081456,0.790763,-0.009298,0.090486,0.728440,-0.043749,0.087880,0.724020,-0.019993
8,ifss2s,30,0.080823,0.792046,0.066656,0.048198,0.923210,0.403834,0.067832,0.857985,...,-0.118553,0.077434,0.781683,0.069463,0.087063,0.704263,0.000492,0.086659,0.721007,0.013516
9,ngcm,30,0.080672,0.825843,0.057531,0.051608,0.949433,0.345143,0.070289,0.884419,...,-0.157105,0.078540,0.816022,0.026834,0.090278,0.737108,-0.041352,0.091170,0.700882,-0.058174

In [9]:
print(df.columns)
df

Index(['model_label', 'horizon', 'brier', 'brier_fair', 'rps', 'rps_fair',
       'auc', 'fair_brier_skill', 'fair_rps_skill'],
      dtype='object')

,model_label,horizon,brier,brier_fair,rps,rps_fair,auc,fair_brier_skill,fair_rps_skill
0,clim,15,0.084715,0.084164,0.276672,0.274260,0.927417,0.000000,0.000000
1,clim_fuxi,15,0.088351,0.087816,0.295445,0.293145,0.925565,-0.043391,-0.068856
2,clim_ifs,15,0.086542,0.085998,0.285312,0.282955,0.924928,-0.021799,-0.031701
3,cond,15,0.081081,0.080195,0.248493,0.245672,0.934845,0.047157,0.104239
4,fuxis2s,15,0.093691,0.093154,0.291807,0.290425,0.905029,-0.060789,0.009277
5,gencast,15,0.074824,0.073909,0.220073,0.217526,0.946233,0.121842,0.206863
6,ifss2s,15,0.077657,0.072277,0.227456,0.213072,0.934997,0.159556,0.246976
7,ngcm,15,0.075059,0.073883,0.217619,0.214311,0.948857,0.122147,0.218585
8,clim,30,0.086048,0.085433,0.573473,0.568363,0.861738,0.000000,0.000000
9,clim_fuxi,30,0.089345,0.088734,0.632040,0.627041,0.851077,-0.038641,-0.103240
10,clim_ifs,30,0.088021,0.087408,0.600146,0.595100,0.854970,-0.023126,-0.047042
11,cond,30,0.083478,0.082655,0.550053,0.544257,0.871427,0.032516,0.042413
12,fuxis2s,30,0.098971,0.097944,0.722453,0.716952,0.815478,-0.103789,-0.143390
13,gencast,30,0.085182,0.083900,0.600847,0.592844,0.870985,0.017939,-0.043073
14,ifss2s,30,0.087468,0.080919,0.578537,0.539833,0.854224,0.074241,0.092870
15,ngcm,30,0.083970,0.082535,0.560482,0.551482,0.876835,0.033915,0.029702

### Fig 1

In [3]:
file_30day_r = f"{root_dir}/fig_data/deterministic_scores_15_day_2019_2024.mat"
data_30_r = sio.loadmat(file_30day_r)

print(data_30_r.keys())
print(data_30_r["mae_cmz_fixed_clim"])
print(data_30_r["std_er_fixed_clim"])
print(data_30_r['mae_cmz_mean_15'])
print(['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'])
data_30_r["mae_avg_15"][:,:,3].transpose()

dict_keys(['__header__', '__version__', '__globals__', 'false_alarm_15', 'far_cmz_mean_15', 'lat', 'lon', 'mae_avg_15', 'mae_cmz_fixed_clim', 'mae_cmz_mean_15', 'mae_yr_15', 'miss_rate_15', 'mr_cmz_mean_15', 'std_er_15', 'std_er_fixed_clim'])
[[7.18333333]]
[[0.9686474]]
[[5.68293651 3.79627425 3.9192328  3.13102183 4.49211052 3.06161155
  3.75384149 3.38844346]]
['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM']

array([[        nan,         nan,  5.43333333, 37.23333333,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  6.6       ,  7.6       ,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  5.5       ,  4.05      ,  1.125     ,  4.86111111,
                nan,         nan,         nan,         nan],
       [ 1.33333333,  7.        ,  2.86944444,  2.25833333,  2.09166667,
         5.51666667,         nan,         nan,         nan],
       [ 4.55555556,  0.66666667,  3.86666667,  4.13611111,  2.24206349,
         4.68525132,  2.46666667,  4.74742063,         nan],
       [ 1.5       , 12.        ,  4.4       ,  3.18888889,  4.07777778,
         2.        ,  2.725     ,  3.07222222,         nan],
       [        nan, 18.97333333, 16.25      ,         nan,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  0.        ,         nan,         nan,         nan,
                nan,         nan,         nan,         nan]])

In [5]:
file_30day = f"{root_dir}/output/deterministic_scores_15_day_2019_2024.mat"
data_30 = sio.loadmat(file_30day)

print(data_30.keys())
print(data_30["mae_cmz_fixed_clim"])
print(data_30["std_er_fixed_clim"])
print(["Clim", 'IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'])
print(data_30['mae_cmz_mean_15'])
data_30["mae_avg_15"][:,:,3].transpose()

dict_keys(['__header__', '__version__', '__globals__', 'false_alarm_15', 'far_cmz_mean_15', 'lat', 'lon', 'mae_avg_15', 'mae_cmz_fixed_clim', 'mae_cmz_mean_15', 'mae_yr_15', 'miss_rate_15', 'mr_cmz_mean_15', 'std_er_15', 'std_er_fixed_clim'])
[[7.18333333]]
[[0.9686474]]
['Clim', 'IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM']
[[5.68293651 3.80512346 3.9192328  3.13102183 4.49211052 3.06161155
  3.65138889 3.39499108]]

array([[        nan,         nan,  5.43333333, 37.23333333,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  6.6       ,  7.6       ,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  5.5       ,  4.05      ,  1.125     ,  4.86111111,
                nan,         nan,         nan,         nan],
       [ 1.33333333,  7.        ,  2.86944444,  2.25833333,  2.09166667,
         5.51666667,         nan,         nan,         nan],
       [ 4.55555556,  0.66666667,  3.86666667,  4.13611111,  2.24206349,
         4.68525132,  2.46666667,  4.74742063,         nan],
       [ 1.5       , 12.        ,  4.4       ,  3.18888889,  4.07777778,
         2.        ,  2.725     ,  3.07222222,         nan],
       [        nan, 18.97333333, 16.25      ,         nan,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  0.        ,         nan,         nan,         nan,
                nan,         nan,         nan,         nan]])

In [83]:
model_num=7
print(["Clim", 'IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'][model_num])
data_30["mae_cmz_mean_30"][0][model_num] - data_30_r["mae_cmz_mean_30"][0][model_num]

NGCM

IndexError: index 7 is out of bounds for axis 0 with size 7

In [31]:
data_30_r["mae_avg_15"][:,:,1].transpose()

array([[        nan,         nan,  3.53333333, 34.99069688,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  5.05571429,  7.77878788,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  3.27619048,  3.67222222,  3.93333333,  6.06928571,
                nan,         nan,         nan,         nan],
       [ 3.88888889,  2.51666667,  4.18      ,  2.27666667,  1.95666667,
         5.6769697 ,         nan,         nan,         nan],
       [ 2.36666667,  2.625     ,  5.55166667,  2.67666667,  2.97380952,
         7.14285714,  1.55      ,  3.82357143,         nan],
       [ 6.86111111,  4.75      ,  7.08944444,  3.79444444,  4.3       ,
         2.5       ,  2.11666667,  2.21666667,         nan],
       [        nan, 21.7169697 , 11.75      ,  5.38333333,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  0.        ,         nan,         nan,         nan,
                nan,         nan,         nan,         nan]])

### Figure 3

In [36]:
import scipy.io as sio
weekly_file = f"{root_dir}/fig_data/5day_forecastwindow_cmz_2019_2024.mat"
data = sio.loadmat(weekly_file)
mae_cmz = data['mae_cmz']  # Shape should be (6, 8) for 6 time periods, 8 models
far_cmz = data['far_cmz']  # Shape should be (6, 8)
mr_cmz = data['mr_cmz']    # Shape should be (4, 8) for 4 weeks
std_er = data['std_er']    # Standard errors for MAE

print(data["model_str"])
far_cmz

[[array(['clim'], dtype='<U4')]
 [array(['ifs'], dtype='<U3')]
 [array(['aifs'], dtype='<U4')]
 [array(['fuxi'], dtype='<U4')]
 [array(['graphcast'], dtype='<U9')]
 [array(['gencast'], dtype='<U7')]
 [array(['fuxis2s'], dtype='<U7')]
 [array(['ngcm51'], dtype='<U6')]]

array([[ 5.00552672,  5.14806667,  6.14221866,  1.61055272,  8.92096044,
         4.60774198,  3.59489348,  5.85507257],
       [ 7.95982277,  8.78547899,  8.85290505,  4.26848899, 11.39773605,
         6.4457009 ,  6.9739043 ,  7.40127785],
       [10.5148626 ,  7.35800489, 12.77523487,  6.54565838, 13.09821372,
         4.49552206,  6.85812311,  4.00694431],
       [12.0407337 ,  6.28736664, 12.38162626, 13.88521342, 24.13860657,
         6.12166779, 11.62840659,  6.82676204],
       [14.46997348,  7.46808236, 17.49078923, 15.73044724, 27.4567295 ,
         6.41197107, 11.71757763, 10.33545782],
       [16.13182367, 10.74482817, 23.85337689, 20.23400135, 17.59355116,
         9.77286226, 18.68398268,  6.96542738]])